### ISSUE TITLE
Consider not including async-redis by default

### ISSUE THREAD

**Issue by trevorturk** [socketry/async-job#5]
I'm attempting to use `async-job-adapter-active_job` with `Async::Job::Processor::Inline` only, but noticed my Bunder install comes with `async-redis`. Not a big deal, but worth considering if requiring by default is necessary.

**Comment by ioquatix** [comment]
Yeah I’ve been thinking about that too. It’s not essential enough.

**Comment by ioquatix** [comment]
Extracted: https://github.com/socketry/async-job-processor-redis
